---
# This playbook deploys a php enabled web server. 

- hosts: all
  user: vagrant
  become: yes

  vars:
    document_root: /vagrant/wwwroot


  tasks:

    - name: be sure kernel packages are latest
      yum:
        name: kernel
        state: latest
      notify:
        - reboot

    - name: be sure all packages are latest
      yum:
        name: "*"
        state: latest

    - name: be sure epel package is installed
      yum: name={{item}} state=installed
      with_items:
        - epel-release

    - name: be sure remi package is installed
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

    - name: be sure php 5.6 packages are installed
      yum:
        enablerepo: remi,remi-php56
        name: "{{ item }}"
        state: installed
      with_items:
        - php
        - php-mbstring
        - php-fpm

    - name: be sure php-fpm is configured
      lineinfile:
        dest: /etc/php-fpm.d/www.conf
        state: present
        backrefs: yes
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - regexp: "^(;|)listen ="
          line: "listen = /var/run/php-fpm/php-fpm.sock"
        - regexp: "^(;|)listen.owner ="
          line: "listen.owner = nginx"
        - regexp: "^(;|)listen.group ="
          line: "listen.owner = nginx"
        - regexp: "^(;|)listen.mode ="
          line: "listen.mode = 0660"
      notify:
        - restart php-fpm

    - name: be sure nginx packages are installed
      yum:
        name: nginx
        state: installed

    - name: be sure document root directory is exists
      file:
        path: "{{ document_root }}"
        state: directory
        owner: nginx
        group: nginx
        mode: 0660

    - name: be sure nginx configuration file is exists
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - restart nginx

    - name: be sure php-fpm service is started and enabled
      service:
        name: php-fpm
        state: running
        enabled: yes

    - name: be sure nginx service is started and enabled
      service:
        name: nginx
        state: running
        enabled: yes


  handlers:

    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: reboot
      command: reboot
